workflows:
  android-apk:
    name: Build Android APK
    max_build_duration: 60
    scripts:
      - script: flutter pub get
      - script: flutter build apk

  ios-workflow:
    name: Build iOS
    max_build_duration: 120
    scripts:
      - script: flutter pub get
      - script: cd ios && pod install
      - script: flutter build ios
