workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        GRADLE_OPTS: "-Xmx6144m -XX:MaxMetaspaceSize=1024m"
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app

  android-apk:
    name: Android APK Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    environment:
      flutter: stable
      vars:
        GRADLE_OPTS: "-Xmx6144m -XX:MaxMetaspaceSize=1024m"
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk

  android-aab:
    name: Android App Bundle (AAB) Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'release/*'
          include: true
      tag_patterns:
        - pattern: 'v*.*.*'
          include: true
    environment:
      flutter: stable
      # Android code signing configuration
      # This references the keystore uploaded to Codemagic dashboard
      # Reference name MUST be exactly: gud-release-key
      # See CODEMAGIC_KEYSTORE_SETUP.md for setup instructions
      android_signing:
        - gud-release-key  # Must match the reference name in Codemagic dashboard
      vars:
        GRADLE_OPTS: "-Xmx6144m -XX:MaxMetaspaceSize=1024m"
    scripts:
      # Create key.properties file with keystore credentials
      # Codemagic automatically injects these environment variables when
      # a keystore with reference name 'gud-release-key' is found:
      # - $CM_KEYSTORE_PASSWORD: Keystore password from Codemagic
      # - $CM_KEY_PASSWORD: Key password from Codemagic
      # - $CM_KEY_ALIAS: Key alias from Codemagic
      # - $CM_KEYSTORE_PATH: Path to keystore file during build
      - name: Set up key.properties
        script: |
          echo "storePassword=$CM_KEYSTORE_PASSWORD" > android/key.properties
          echo "keyPassword=$CM_KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$CM_KEY_ALIAS" >> android/key.properties
          echo "storeFile=$CM_KEYSTORE_PATH" >> android/key.properties
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release
      - name: Verify AAB
        script: |
          if [ -f "build/app/outputs/bundle/release/app-release.aab" ]; then
            echo "✅ AAB build successful"
            ls -lh build/app/outputs/bundle/release/app-release.aab
          else
            echo "❌ AAB build failed"
            exit 1
          fi
    artifacts:
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - developer@example.com  # Update with actual email address