// Mocks generated by Mockito 5.4.0 from annotations
// in gud_app/test/unit/auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseFirestore_0 extends _i1.SmartFake
    implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeUser_1 extends _i1.SmartFake implements _i3.User {
  _FakeUser_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeUserCredential_2 extends _i1.SmartFake implements _i3.UserCredential {
  _FakeUserCredential_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeDocumentReference_3<T extends Object?>
    extends _i1.SmartFake implements _i2.DocumentReference<T> {
  _FakeDocumentReference_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeDocumentSnapshot_4<T extends Object?>
    extends _i1.SmartFake implements _i2.DocumentSnapshot<T> {
  _FakeDocumentSnapshot_4(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeCollectionReference_5<T extends Object?>
    extends _i1.SmartFake implements _i2.CollectionReference<T> {
  _FakeCollectionReference_5(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [FirebaseAuth].
class MockFirebaseAuth extends _i1.Mock implements _i3.FirebaseAuth {
  MockFirebaseAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.User? get currentUser => (super.noSuchMethod(Invocation.getter(#currentUser))
      as _i3.User?);

  @override
  _i4.Stream<_i3.User?> authStateChanges() => (super.noSuchMethod(
        Invocation.method(#authStateChanges, []),
        returnValue: _i4.Stream<_i3.User?>.empty(),
      ) as _i4.Stream<_i3.User?>);

  @override
  _i4.Future<_i3.UserCredential> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#signInWithEmailAndPassword, [],
            {#email: email, #password: password}),
        returnValue: _i4.Future<_i3.UserCredential>.value(_FakeUserCredential_2(
            this, Invocation.method(#signInWithEmailAndPassword, [],
                {#email: email, #password: password}))),
      ) as _i4.Future<_i3.UserCredential>);

  @override
  _i4.Future<_i3.UserCredential> createUserWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#createUserWithEmailAndPassword, [],
            {#email: email, #password: password}),
        returnValue: _i4.Future<_i3.UserCredential>.value(_FakeUserCredential_2(
            this, Invocation.method(#createUserWithEmailAndPassword, [],
                {#email: email, #password: password}))),
      ) as _i4.Future<_i3.UserCredential>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(#signOut, []),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendPasswordResetEmail({required String? email}) =>
      (super.noSuchMethod(
        Invocation.method(#sendPasswordResetEmail, [], {#email: email}),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [FirebaseFirestore].
class MockFirebaseFirestore extends _i1.Mock implements _i2.FirebaseFirestore {
  MockFirebaseFirestore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CollectionReference<Map<String, dynamic>> collection(String? path) =>
      (super.noSuchMethod(
        Invocation.method(#collection, [path]),
        returnValue: _FakeCollectionReference_5<Map<String, dynamic>>(
            this, Invocation.method(#collection, [path])),
      ) as _i2.CollectionReference<Map<String, dynamic>>);
}

/// A class which mocks [UserCredential].
class MockUserCredential extends _i1.Mock implements _i3.UserCredential {
  MockUserCredential() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.User? get user => (super.noSuchMethod(Invocation.getter(#user)) as _i3.User?);
}

/// A class which mocks [User].
class MockUser extends _i1.Mock implements _i3.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get uid => (super.noSuchMethod(
        Invocation.getter(#uid),
        returnValue: '',
      ) as String);

  @override
  String? get email => (super.noSuchMethod(Invocation.getter(#email)) as String?);
}

/// A class which mocks [DocumentReference].
class MockDocumentReference<T extends Object?> extends _i1.Mock
    implements _i2.DocumentReference<T> {
  MockDocumentReference() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> set(T? data, [_i2.SetOptions? options]) => (super.noSuchMethod(
        Invocation.method(#set, [data, options]),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.DocumentSnapshot<T>> get() => (super.noSuchMethod(
        Invocation.method(#get, []),
        returnValue: _i4.Future<_i2.DocumentSnapshot<T>>.value(
            _FakeDocumentSnapshot_4<T>(this, Invocation.method(#get, []))),
      ) as _i4.Future<_i2.DocumentSnapshot<T>>);

  @override
  _i4.Future<void> update(Map<String, dynamic>? data) => (super.noSuchMethod(
        Invocation.method(#update, [data]),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [DocumentSnapshot].
class MockDocumentSnapshot<T extends Object?> extends _i1.Mock
    implements _i2.DocumentSnapshot<T> {
  MockDocumentSnapshot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  T? data() => (super.noSuchMethod(Invocation.method(#data, [])) as T?);

  @override
  bool get exists => (super.noSuchMethod(
        Invocation.getter(#exists),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [CollectionReference].
class MockCollectionReference<T extends Object?> extends _i1.Mock
    implements _i2.CollectionReference<T> {
  MockCollectionReference() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DocumentReference<T> doc([String? path]) => (super.noSuchMethod(
        Invocation.method(#doc, [path]),
        returnValue: _FakeDocumentReference_3<T>(
            this, Invocation.method(#doc, [path])),
      ) as _i2.DocumentReference<T>);
}
