// Mocks generated by Mockito 5.4.0 from annotations
// in gud_app/test/unit/firestore_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDocumentReference_0<T extends Object?>
    extends _i1.SmartFake implements _i2.DocumentReference<T> {
  _FakeDocumentReference_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeDocumentSnapshot_1<T extends Object?>
    extends _i1.SmartFake implements _i2.DocumentSnapshot<T> {
  _FakeDocumentSnapshot_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeQuerySnapshot_2<T extends Object?>
    extends _i1.SmartFake implements _i2.QuerySnapshot<T> {
  _FakeQuerySnapshot_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeQuery_3<T extends Object?>
    extends _i1.SmartFake implements _i2.Query<T> {
  _FakeQuery_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeCollectionReference_4<T extends Object?>
    extends _i1.SmartFake implements _i2.CollectionReference<T> {
  _FakeCollectionReference_4(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [FirebaseFirestore].
class MockFirebaseFirestore extends _i1.Mock implements _i2.FirebaseFirestore {
  MockFirebaseFirestore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CollectionReference<Map<String, dynamic>> collection(String? path) =>
      (super.noSuchMethod(
        Invocation.method(#collection, [path]),
        returnValue: _FakeCollectionReference_4<Map<String, dynamic>>(
            this, Invocation.method(#collection, [path])),
      ) as _i2.CollectionReference<Map<String, dynamic>>);
}

/// A class which mocks [CollectionReference].
class MockCollectionReference<T extends Object?> extends _i1.Mock
    implements _i2.CollectionReference<T> {
  MockCollectionReference() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DocumentReference<T> doc([String? path]) => (super.noSuchMethod(
        Invocation.method(#doc, [path]),
        returnValue: _FakeDocumentReference_0<T>(
            this, Invocation.method(#doc, [path])),
      ) as _i2.DocumentReference<T>);

  @override
  _i3.Future<_i2.DocumentReference<T>> add(T? data) => (super.noSuchMethod(
        Invocation.method(#add, [data]),
        returnValue: _i3.Future<_i2.DocumentReference<T>>.value(
            _FakeDocumentReference_0<T>(this, Invocation.method(#add, [data]))),
      ) as _i3.Future<_i2.DocumentReference<T>>);

  @override
  _i3.Stream<_i2.QuerySnapshot<T>> snapshots() => (super.noSuchMethod(
        Invocation.method(#snapshots, []),
        returnValue: _i3.Stream<_i2.QuerySnapshot<T>>.empty(),
      ) as _i3.Stream<_i2.QuerySnapshot<T>>);

  @override
  _i2.Query<T> where(
    Object? field, {
    Object? isEqualTo,
    Object? isNotEqualTo,
    Object? isLessThan,
    Object? isLessThanOrEqualTo,
    Object? isGreaterThan,
    Object? isGreaterThanOrEqualTo,
    Object? arrayContains,
    List<Object?>? arrayContainsAny,
    List<Object?>? whereIn,
    List<Object?>? whereNotIn,
    bool? isNull,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#where, [field], {
          #isEqualTo: isEqualTo,
          #isNotEqualTo: isNotEqualTo,
          #isLessThan: isLessThan,
          #isLessThanOrEqualTo: isLessThanOrEqualTo,
          #isGreaterThan: isGreaterThan,
          #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
          #arrayContains: arrayContains,
          #arrayContainsAny: arrayContainsAny,
          #whereIn: whereIn,
          #whereNotIn: whereNotIn,
          #isNull: isNull,
        }),
        returnValue: _FakeQuery_3<T>(this, Invocation.method(#where, [field])),
      ) as _i2.Query<T>);

  @override
  _i2.Query<T> orderBy(
    Object? field, {
    bool? descending = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#orderBy, [field], {#descending: descending}),
        returnValue: _FakeQuery_3<T>(
            this, Invocation.method(#orderBy, [field], {#descending: descending})),
      ) as _i2.Query<T>);

  @override
  _i2.Query<T> limit(int? limit) => (super.noSuchMethod(
        Invocation.method(#limit, [limit]),
        returnValue: _FakeQuery_3<T>(this, Invocation.method(#limit, [limit])),
      ) as _i2.Query<T>);
}

/// A class which mocks [DocumentReference].
class MockDocumentReference<T extends Object?> extends _i1.Mock
    implements _i2.DocumentReference<T> {
  MockDocumentReference() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: '',
      ) as String);

  @override
  _i3.Future<void> set(T? data, [_i2.SetOptions? options]) => (super.noSuchMethod(
        Invocation.method(#set, [data, options]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i2.DocumentSnapshot<T>> get() => (super.noSuchMethod(
        Invocation.method(#get, []),
        returnValue: _i3.Future<_i2.DocumentSnapshot<T>>.value(
            _FakeDocumentSnapshot_1<T>(this, Invocation.method(#get, []))),
      ) as _i3.Future<_i2.DocumentSnapshot<T>>);

  @override
  _i3.Future<void> update(Map<String, dynamic>? data) => (super.noSuchMethod(
        Invocation.method(#update, [data]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> delete() => (super.noSuchMethod(
        Invocation.method(#delete, []),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [DocumentSnapshot].
class MockDocumentSnapshot<T extends Object?> extends _i1.Mock
    implements _i2.DocumentSnapshot<T> {
  MockDocumentSnapshot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: '',
      ) as String);

  @override
  T? data() => (super.noSuchMethod(Invocation.method(#data, [])) as T?);

  @override
  bool get exists => (super.noSuchMethod(
        Invocation.getter(#exists),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [QuerySnapshot].
class MockQuerySnapshot<T extends Object?> extends _i1.Mock
    implements _i2.QuerySnapshot<T> {
  MockQuerySnapshot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.QueryDocumentSnapshot<T>> get docs => (super.noSuchMethod(
        Invocation.getter(#docs),
        returnValue: <_i2.QueryDocumentSnapshot<T>>[],
      ) as List<_i2.QueryDocumentSnapshot<T>>);
}

/// A class which mocks [QueryDocumentSnapshot].
class MockQueryDocumentSnapshot<T extends Object?> extends _i1.Mock
    implements _i2.QueryDocumentSnapshot<T> {
  MockQueryDocumentSnapshot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: '',
      ) as String);

  @override
  T data() => (super.noSuchMethod(
        Invocation.method(#data, []),
        returnValue: {} as T,
      ) as T);

  @override
  bool get exists => (super.noSuchMethod(
        Invocation.getter(#exists),
        returnValue: true,
      ) as bool);
}

/// A class which mocks [Query].
class MockQuery<T extends Object?> extends _i1.Mock implements _i2.Query<T> {
  MockQuery() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i2.QuerySnapshot<T>> snapshots() => (super.noSuchMethod(
        Invocation.method(#snapshots, []),
        returnValue: _i3.Stream<_i2.QuerySnapshot<T>>.empty(),
      ) as _i3.Stream<_i2.QuerySnapshot<T>>);

  @override
  _i3.Future<_i2.QuerySnapshot<T>> get() => (super.noSuchMethod(
        Invocation.method(#get, []),
        returnValue: _i3.Future<_i2.QuerySnapshot<T>>.value(
            _FakeQuerySnapshot_2<T>(this, Invocation.method(#get, []))),
      ) as _i3.Future<_i2.QuerySnapshot<T>>);

  @override
  _i2.Query<T> where(
    Object? field, {
    Object? isEqualTo,
    Object? isNotEqualTo,
    Object? isLessThan,
    Object? isLessThanOrEqualTo,
    Object? isGreaterThan,
    Object? isGreaterThanOrEqualTo,
    Object? arrayContains,
    List<Object?>? arrayContainsAny,
    List<Object?>? whereIn,
    List<Object?>? whereNotIn,
    bool? isNull,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#where, [field], {
          #isEqualTo: isEqualTo,
          #isNotEqualTo: isNotEqualTo,
          #isLessThan: isLessThan,
          #isLessThanOrEqualTo: isLessThanOrEqualTo,
          #isGreaterThan: isGreaterThan,
          #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
          #arrayContains: arrayContains,
          #arrayContainsAny: arrayContainsAny,
          #whereIn: whereIn,
          #whereNotIn: whereNotIn,
          #isNull: isNull,
        }),
        returnValue: _FakeQuery_3<T>(this, Invocation.method(#where, [field])),
      ) as _i2.Query<T>);

  @override
  _i2.Query<T> orderBy(
    Object? field, {
    bool? descending = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#orderBy, [field], {#descending: descending}),
        returnValue: _FakeQuery_3<T>(
            this, Invocation.method(#orderBy, [field], {#descending: descending})),
      ) as _i2.Query<T>);

  @override
  _i2.Query<T> limit(int? limit) => (super.noSuchMethod(
        Invocation.method(#limit, [limit]),
        returnValue: _FakeQuery_3<T>(this, Invocation.method(#limit, [limit])),
      ) as _i2.Query<T>);
}
