// Mocks generated by Mockito 5.4.0 from annotations
// in gud_app/test/unit/storage_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:firebase_storage/firebase_storage.dart' as _i2;
import 'package:image_picker/image_picker.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeReference_0 extends _i1.SmartFake implements _i2.Reference {
  _FakeReference_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeUploadTask_1 extends _i1.SmartFake implements _i2.UploadTask {
  _FakeUploadTask_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeTaskSnapshot_2 extends _i1.SmartFake implements _i2.TaskSnapshot {
  _FakeTaskSnapshot_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeXFile_3 extends _i1.SmartFake implements _i3.XFile {
  _FakeXFile_3(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [FirebaseStorage].
class MockFirebaseStorage extends _i1.Mock implements _i2.FirebaseStorage {
  MockFirebaseStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Reference ref([String? path]) => (super.noSuchMethod(
        Invocation.method(#ref, [path]),
        returnValue: _FakeReference_0(this, Invocation.method(#ref, [path])),
      ) as _i2.Reference);

  @override
  _i2.Reference refFromURL(String? url) => (super.noSuchMethod(
        Invocation.method(#refFromURL, [url]),
        returnValue: _FakeReference_0(this, Invocation.method(#refFromURL, [url])),
      ) as _i2.Reference);
}

/// A class which mocks [Reference].
class MockReference extends _i1.Mock implements _i2.Reference {
  MockReference() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get fullPath => (super.noSuchMethod(
        Invocation.getter(#fullPath),
        returnValue: '',
      ) as String);

  @override
  _i2.Reference child(String? path) => (super.noSuchMethod(
        Invocation.method(#child, [path]),
        returnValue: _FakeReference_0(this, Invocation.method(#child, [path])),
      ) as _i2.Reference);

  @override
  _i2.UploadTask putFile(dynamic file, [_i2.SettableMetadata? metadata]) =>
      (super.noSuchMethod(
        Invocation.method(#putFile, [file, metadata]),
        returnValue: _FakeUploadTask_1(
            this, Invocation.method(#putFile, [file, metadata])),
      ) as _i2.UploadTask);

  @override
  _i2.UploadTask putData(_i5.Uint8List? data, [_i2.SettableMetadata? metadata]) =>
      (super.noSuchMethod(
        Invocation.method(#putData, [data, metadata]),
        returnValue: _FakeUploadTask_1(
            this, Invocation.method(#putData, [data, metadata])),
      ) as _i2.UploadTask);

  @override
  _i4.Future<String> getDownloadURL() => (super.noSuchMethod(
        Invocation.method(#getDownloadURL, []),
        returnValue: _i4.Future<String>.value(''),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> delete() => (super.noSuchMethod(
        Invocation.method(#delete, []),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [UploadTask].
class MockUploadTask extends _i1.Mock implements _i2.UploadTask {
  MockUploadTask() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.TaskSnapshot> get snapshot => (super.noSuchMethod(
        Invocation.getter(#snapshot),
        returnValue: _i4.Future<_i2.TaskSnapshot>.value(
            _FakeTaskSnapshot_2(this, Invocation.getter(#snapshot))),
      ) as _i4.Future<_i2.TaskSnapshot>);

  @override
  _i4.Stream<_i2.TaskSnapshot> get snapshotEvents => (super.noSuchMethod(
        Invocation.getter(#snapshotEvents),
        returnValue: _i4.Stream<_i2.TaskSnapshot>.empty(),
      ) as _i4.Stream<_i2.TaskSnapshot>);

  @override
  _i4.Future<_i2.TaskSnapshot> whenComplete() => (super.noSuchMethod(
        Invocation.method(#whenComplete, []),
        returnValue: _i4.Future<_i2.TaskSnapshot>.value(
            _FakeTaskSnapshot_2(this, Invocation.method(#whenComplete, []))),
      ) as _i4.Future<_i2.TaskSnapshot>);
}

/// A class which mocks [TaskSnapshot].
class MockTaskSnapshot extends _i1.Mock implements _i2.TaskSnapshot {
  MockTaskSnapshot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Reference get ref => (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeReference_0(this, Invocation.getter(#ref)),
      ) as _i2.Reference);

  @override
  int get bytesTransferred => (super.noSuchMethod(
        Invocation.getter(#bytesTransferred),
        returnValue: 0,
      ) as int);

  @override
  int get totalBytes => (super.noSuchMethod(
        Invocation.getter(#totalBytes),
        returnValue: 0,
      ) as int);
}

/// A class which mocks [ImagePicker].
class MockImagePicker extends _i1.Mock implements _i3.ImagePicker {
  MockImagePicker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i3.XFile?> pickImage({
    required _i3.ImageSource? source,
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    _i3.CameraDevice? preferredCameraDevice = _i3.CameraDevice.rear,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#pickImage, [], {
          #source: source,
          #maxWidth: maxWidth,
          #maxHeight: maxHeight,
          #imageQuality: imageQuality,
          #preferredCameraDevice: preferredCameraDevice,
        }),
        returnValue: _i4.Future<_i3.XFile?>.value(),
      ) as _i4.Future<_i3.XFile?>);

  @override
  _i4.Future<List<_i3.XFile>> pickMultiImage({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#pickMultiImage, [], {
          #maxWidth: maxWidth,
          #maxHeight: maxHeight,
          #imageQuality: imageQuality,
        }),
        returnValue: _i4.Future<List<_i3.XFile>>.value(<_i3.XFile>[]),
      ) as _i4.Future<List<_i3.XFile>>);

  @override
  _i4.Future<_i3.XFile?> pickVideo({
    required _i3.ImageSource? source,
    _i3.CameraDevice? preferredCameraDevice = _i3.CameraDevice.rear,
    Duration? maxDuration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#pickVideo, [], {
          #source: source,
          #preferredCameraDevice: preferredCameraDevice,
          #maxDuration: maxDuration,
        }),
        returnValue: _i4.Future<_i3.XFile?>.value(),
      ) as _i4.Future<_i3.XFile?>);
}
